[package]
name = "common-federation-api"
version = "0.16.0"
description = "Serializable types for the endpoints in the Matrix server-server API."
categories = ["api-bindings", "web-programming"]
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
repository = "https://github.com/ruma/ruma"
edition = "2024"
rust-version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[features]
default = []

# `OutgoingRequest` / `IncomingResponse` impls, for code talking to a homeserver.
client = ["common-types/client"]
# `IncomingRequest` / `OutgoingResponse` impls, for code answering requests.
server = ["common-types/server"]

# Allow the `pdus` field in a federation transaction request to be missing.
compat-optional-txn-pdus = []
unstable-msc3618 = []
unstable-msc3723 = []
unstable-msc3843 = ["common-types/unstable-msc3843"]
unstable-msc4125 = []
# Selective Presence
unstable-msc4495 = ["common-types/unstable-msc4495", "common-events/unstable-msc4495"]

[dependencies]
common-types = { path = "../common-types", version = "0.16.0" }
common-events = { path = "../common-events", version = "0.16.0" }
common-signatures = { path = "../common-signatures", version = "0.16.0" }
bytes = "1.11.1"
headers = "0.4.0"
http = { workspace = true, features = ["std"] }
http-auth = { version = "0.1.9", default-features = false }
httparse = "1.9.0"
js_int = { version = "0.2.2", features = ["serde"] }
memchr = "2.7.0"
mime.workspace = true
rand = { workspace = true, features = ["sys_rng"] }
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true
tracing = { workspace = true, features = ["attributes"] }

[dev-dependencies]
assert_matches2.workspace = true
common-ruma = { path = "../common-ruma", features = ["full"] }

[lints]
workspace = true
