coverage:
  status:
    project:
      default:
        # by default, we only care about test coverage of the main
        # rust crates
        target: auto
        threshold: 1%
        paths:
          - "crates/client-matrix/"
          - "crates/client-base/"
          - "crates/client-common/"
          - "crates/client-crypto/"
          - "crates/client-qrcode/"
          - "crates/client-sqlite/"
          - "crates/client-store-encryption/"
          # Coverage of wasm tests isn't supported at the moment,
          # see rustwasm/wasm-bindgen#2276
          # - "crates/client-indexeddb"
      bindings:
        # Coverage of binding tests is recorded but for informational
        # purposes only
        informational: true
        paths:
          - "bindings/"
    patch: off
ignore:
  - "bindings/client-crypto-ffi"
  - "bindings/client-matrix-ffi"
  - "crates/client-indexeddb"
  - "testing"
  - "xtask"
