coverage:
  status:
    project:
      default:
        # by default, we only care about test coverage of the main
        # rust crates
        target: auto
        threshold: 1%
        paths:
          - "crates/client/"
          - "crates/common/"
          - "crates/server/"
          - "crates/macros/"
      bindings:
        # Coverage of binding tests is recorded but for informational
        # purposes only
        informational: true
        paths:
          - "bindings/"
    patch: off
ignore:
  - "bindings/client-crypto-ffi"
  - "bindings/client-matrix-ffi"
  # Coverage of wasm tests isn't supported at the moment,
  # see rustwasm/wasm-bindgen#2276
  - "crates/client/src/indexeddb"
  - "testing"
  - "xtask"
