coverage:
  status:
    project:
      default:
        # by default, we only care about test coverage of the main
        # rust crates
        target: auto
        threshold: 1%
        paths:
          - "crates/matrix/"
          - "crates/base/"
          - "crates/sdk-common/"
          - "crates/crypto/"
          - "crates/qrcode/"
          - "crates/sqlite/"
          - "crates/store-encryption/"
          # Coverage of wasm tests isn't supported at the moment,
          # see rustwasm/wasm-bindgen#2276
          # - "crates/indexeddb"
      bindings:
        # Coverage of binding tests is recorded but for informational
        # purposes only
        informational: true
        paths:
          - "bindings/"
    patch: off
ignore:
  - "bindings/crypto-ffi"
  - "bindings/matrix-ffi"
  - "crates/indexeddb"
  - "testing"
  - "xtask"
