[default-config]
debug = false
verbose = false
exclude-files = [
    "examples/*",
    "testing/*",
    "labs/*",
    "**/tests/*",
    # wasm only, can't get coverage
    "crates/client/src/indexeddb/*",
    # until it doesn't segfault anymore, this is excluded :(
    "crates/client/src/base/*",
    # test helpers
    "crates/client/src/test/*",
    "crates/common/src/testing.rs",
]
workspace = true
# the sqlite crypto store is not tested otherwise, because it is only switched
# on by crypto-ffi, which is excluded from testing below.
features = "crypto-store"
exclude = [
    # bindings
    "client-crypto-ffi",
    "client-matrix-ffi",
    # repo automation (ci, codegen)
    "uniffi-bindgen",
    "xtask",
]
