[default-config]
debug = false
verbose = false
exclude-files = [
    "examples/*",
    "testing/*",
    "labs/*",
    "**/tests/*",
]
workspace = true
# sqlite crypto store is not tested otherwise because it's only activated by
# crypto-ffi, which is excluded from testing below.
features = "crypto-store"
exclude = [
    # bindings
    "crypto-ffi",
    "matrix-ffi",
    # wasm only, can't get coverage
    "indexeddb",
    # testing
    "sdk-test",
    "sdk-test-macros",
    # repo automation (ci, codegen)
    "uniffi-bindgen",
    "xtask",
    # until it doesn't segfault anymore, this is excluded :(
    "base",
]
