[package]
name = "common-appservice-api"
version = "0.16.0"
description = "Serializable types for the Matrix application service API."
categories = ["api-bindings", "web-programming"]
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
repository = "https://github.com/ruma/ruma"
edition = "2024"
rust-version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[features]
default = []

[dependencies]
common-types = { path = "../common-types" }
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }

[lints]
workspace = true
