[package]
name = "signatures"
version = "0.16.0"
description = "Digital signatures according to the Matrix specification."
categories = ["api-bindings", "web-programming"]
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
repository = "https://github.com/ruma/ruma"
edition = "2024"
rust-version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[features]
default = []

[dependencies]
common = { path = "../common", version = "0.16.0" }
events = { path = "../events", version = "0.16.0" }
base64.workspace = true
ed25519-dalek = { version = "3.0.0", features = ["alloc", "pkcs8"] }
pkcs8 = { version = "0.11.0", features = ["alloc"] }
rand = { workspace = true, features = ["sys_rng"] }
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches2.workspace = true
ruma = { path = "../ruma", features = ["full"] }

[lints]
workspace = true
